markdown: redcarpet
auto: true
redcarpet:
  extensions: ["autolink", "tables", "strikethrough"]
permalink: /:year/:month/:day/:title 
title: zxyx
url: http://zxyx.github.io
githubEditBaseURL: https://github.com/zxyx/zxyx.github.com/edit/master/
subscribe: http://zxyx.github.io/atom.xml
exclude: [ README.md, newpost.rb ]
domain: zxyx.github.io
author: zxyx
email: idaroshan@126.com
googleAnalyticsID: UA-5531632-1
disqusShortname: zxyx
timezone: America/New_York
